

positions:
- analytics engineer
- data engineer
- data scientist
- data analyst

locations:
- Remote
- "Seattle, Washington, United States"

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo

# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)
blacklist:
 - avalara
 - cybercoders

blackListTitles:
- java
- ios
- android


humanintervention:
- True